/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example.firstyearproject;

import javafx.application.Application;
import javafx.stage.Stage;
import org.example.firstyearproject.preloader.PreloaderController;
import org.example.firstyearproject.preloader.PreloaderView;

public class App extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    public Model model;

    @Override
    public void start(Stage primaryStage) {
        PreloaderView preloaderView = new PreloaderView(primaryStage);
        new PreloaderController(preloaderView, primaryStage);
    }

    public void loadMap(String url) throws Exception {
        model = Model.load(url);
        System.out.println("loadMap done");
    }

    public void startMap(Stage primaryStage, String url) throws Exception {
        var view = new View(model, primaryStage);
        view.setUrl(url);
        new Controller(model, view, primaryStage, view.trans);
    }
}
